import http from '@/framework/http'
import paper from "@/views/mobile/exam/Paper.vue";
const examApi = {
    questionSort: { "0": '客观题', "1": '主观题' },
    questionChoice: [{ "1": "单选", "2": "多选", "3": "不定项选", "4": "判断", "5": "定值填空题" }, { '101': '编辑器', '102': '文件上传' }],
    selectors:['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'],
    getBasicList: (params) => http.post('/exam/master/basic/data',params),
    getExamHistoryList: (params) => http.post('/exam/master/history/data',params),
    getExamHistoryDetail: (ehId) => http.post('/exam/master/history/detail',{ehId}),
    delExamHistory: (params) =>  http.post('/exam/master/history/delete',params),
    exportExamHistory:(params) => http.post('/exam/master/history/export',params,{
        responseType: 'blob'
    }),
    getExamHistoryLog: (ehId) => http.post('/exam/master/history/log',{ehId}),
    getExamHistoryFace: (ehId) => http.post('/exam/master/history/face',{ehId}),
    getExamHistory:(ehId) => http.post('/exam/master/history', {ehId}),
    decideHistory: (params) => http.post('/exam/master/basic/decide',params),
    getAiAsnalysis: (params) => http.post('/exam/master/basic/ai',params),
    getBasic: (basicid) => http.post('/exam/master/basic',{basicid}),
    delBasics: (ids) => http.post('/exam/master/basic/delete', {ids}),
    modifyBasic: (basic) => http.post('/exam/master/basic/modify', basic),
    addBasic: (basic) => http.post('/exam/master/basic/add', basic),
    getBasicMonitorList:(params) => http.post('/exam/master/basic/session',params),
    forceSavePaper:(sessionid) => http.post('/exam/master/basic/force',{sessionid}),
    getAllSubjects: () => http.post('/exam/master/subject/all'),
    getSubjectList: (params) => http.post('/exam/master/subject/data',params),
    delSubjects: (ids) => http.post('/exam/master/subject/delete', {ids}),
    modifySubject: (subject) => http.post('/exam/master/subject/modify', subject),
    addSubject: (subject) => http.post('/exam/master/subject/add', subject),
    getSubject: (subjectid) => http.post('/exam/master/subject/subject', {subjectid}),
    refreshSubjectCache: (ids) => http.post('/exam/master/subject/refresh', {ids}),
    getAllSections: (params) => http.post('/exam/master/section/all',params),
    getSectionList: (params) => http.post('/exam/master/section/data',params),
    delSections: (ids) => http.post('/exam/master/section/delete', {ids}),
    modifySection: (section) => http.post('/exam/master/section/modify', section),
    addSection: (section) => http.post('/exam/master/section/add', section),
    getSection: (sectionid) => http.post('/exam/master/section',{sectionid}),
    refreshSectionCache: (ids) => http.post('/exam/master/section/refresh', {ids}),
    getAllPoints: (params) => http.post('/exam/master/point/all',params),
    getPointList: (params) => http.post('/exam/master/point/data',params),
    delPoints: (ids) => http.post('/exam/master/point/delete', {ids}),
    modifyPoint: (point) => http.post('/exam/master/point/modify', point),
    addPoint: (point) => http.post('/exam/master/point/add', point),
    refreshPointCache: (ids) => http.post('/exam/master/point/refresh', {ids}),
    getAllPapers: (params) => http.post('/exam/master/paper/all',params),
    getPaperList: (params) => http.post('/exam/master/paper/data',params),
    delPapers: (ids) => http.post('/exam/master/paper/delete', {ids}),
    modifyPaper: (paper) => http.post('/exam/master/paper/modify', paper),
    addPaper: (paper) => http.post('/exam/master/paper/add', paper),
    getPaper: (paperid) => http.post('/exam/master/paper/paper', {paperid}),
    downloadPaper: (paperid) => http.post('/exam/master/paper/export',{paperid}, {
        responseType: 'blob'
    }),
    getPaperQuestion:(paperid) => http.post('/exam/master/paper/question',{paperid}),
    getAllQuestionTypes: () => http.post('/exam/master/questype/all'),
    getQuestionTypeList: (params) => http.post('/exam/master/questype/data',params),
    delQuestionTypes: (ids) => http.post('/exam/master/questype/delete', {ids}),
    modifyQuestionType: (paper) => http.post('/exam/master/questype/modify', paper),
    addQuestionType: (paper) => http.post('/exam/master/questype/add', paper),
    getQuestionList: (params) => http.post('/exam/master/question/data',params),
    getQuestion:(questionid)=> http.post('/exam/master/question',{questionid}),
    delQuestions: (params) => http.post('/exam/master/question/delete', params),
    delChildren: (ids) => http.post('/exam/master/question/delchildren', {ids}),
    modifyQuestion: (question) => http.post('/exam/master/question/modify', question),
    addQuestion: (question) => http.post('/exam/master/question/add', question),
    importQuestion: (params) => http.post('/exam/master/question/import', params),
    setRelation: (params) => http.post('/exam/master/question/setrelation', params),
    setConfig: (params) => http.post('/exam/master/setting/setconfig', params),
    getConfig: () => http.get('/exam/master/setting/getconfig'),
    getFeedBackList:(params) => http.post('/exam/master/feed/data',params),
    delFeedback:(ids) => http.post('/exam/master/feed/delete',{ids}),
    signFeedback:(ids) => http.post('/exam/master/feed/sign',{ids}),
    getBasicPrice: (basicId) => http.post('/exam/master/price/data',{basicId}),
    addBasicPrice: (params) => http.post('/exam/master/price/add',params),
    modifyBasicPrice: (params) => http.post('/exam/master/price/modify',params),
    delBasicPrice: (ids) => http.post('/exam/master/price/delete',{ids}),
    getMemberList: (params) => http.post('/exam/master/member/data',params),
    addMember: (params) => http.post('/exam/master/member/add',params),
    addMemberByPassport: (params) => http.post('/exam/master/member/addbypassport',params),
    modifyMember: (params) => http.post('/exam/master/member/modify',params),
    deleteMember: (ids) => http.post('/exam/master/member/delete',{ids}),
    refreshNumber: (basicId) => http.post('/exam/master/member/refresh',{basicId}),
};
export default examApi;