import http from '@/framework/http'
const cardApi = {
    getCardSubjects: (search) => http.post('/card',search),
    getStoreSubject: (subjectId) => http.get('/card/storesubject/' + subjectId),
    getStoreSubjects: (params) => http.post('/card/store',params),
    getSubject: (subjectId) => http.get('/card/subject/'+subjectId),
    addCardSubject: (subject) => http.post('/card/addsubject', subject),
    modifyCardSubject: (subject) => http.post('/card/modifysubject', subject),
    delCardSubject: (subjectId) => http.post('/card/delsubject', { ids: [subjectId] }),
    delCardSubjects: (subjectIds) => http.post('/card/delsubject', { ids: subjectIds }),
    getCards: (search) => http.post('/card/cards/',search),
    getStoreCards: (params) => http.post('/card/storecards',params),
    getCard: (cardId) => http.get('/card/card/'+cardId),
    addCard: (card) => http.post('/card/add', card),
    modifyCard: (card) => http.post('/card/modify', card),
    delCard: (cardId) => http.post('/card/del', { ids: [cardId] }),
    delCards: (cardIds) => http.post('/card/del', { ids: cardIds }),
    modifyCardItem: (params) => http.post('/card/modifycarditem',params),
    getCardQuestions: (search) => http.post('/card/cardquestions/',search),
    getCardQuestion: (questionId) => http.get('/card/cardquestion/'+questionId),
    addCardQuestion: (question) => http.post('/card/addcardquestion', question),
    modifyCardQuestion: (question) => http.post('/card/modifycardquestion', question),
    delCardQuestion: (questionId) => http.post('/card/delcardquestion', { ids: [questionId] }),
    delCardQuestions: (questionIds) => http.post('/card/delcardquestion', { ids: questionIds }),
    getCardConcepts: (search) => http.post('/card/cardconcepts/',search),
    getCardConcept: (conceptId) => http.get('/card/cardconcept/'+conceptId),
    addCardConcept: (concept) => http.post('/card/addcardconcept', concept),
    modifyCardConcept: (concept) => http.post('/card/modifycardconcept', concept),
    delCardConcept: (conceptId) => http.post('/card/delcardconcept', { ids: [conceptId] }),
    delCardConcepts: (conceptIds) => http.post('/card/delcardconcept', { ids: conceptIds }),
    getCardExtras: (search) => http.post('/card/cardextras/',search),
    getCardExtra: (extraId) => http.get('/card/cardextra/'+extraId),
    addCardExtra: (extra) => http.post('/card/addcardextra', extra),
    modifyCardExtra: (extra) => http.post('/card/modifycardextra', extra),
    delCardExtra: (extraId) => http.post('/card/delcardextra', { ids: [extraId] }),
    delCardExtras: (extraIds) => http.post('/card/delcardextra', { ids: extraIds }),
};
export default cardApi;