import http from '@/framework/http'
const examApi = {
    setExamSession: (examId) => http.post('/exam/app/index/session',{examId}),
    getBasic: (basicId) => http.post('/exam/app/index/basic',{basicId}),
    getBasicList: (params) => http.post('/exam/app/index/data',params),
    getQuestionTypes: () => http.post('/exam/app/index/type'),
    getBasicPrice: (basicId) => http.post('/exam/app/index/price',{basicId}),
    buyBasic: (priceId) => http.post('/exam/app/index/buy',{priceId}),
    getExamBasic: () => http.post('/exam/app/basic/current'),
    getSectionPoint: () => http.post('/exam/app/basic/point'),
    getQuestionList: (params) => http.post('/exam/app/basic/data',params),
    getQuestionDetail: (questionid) => http.post('/exam/app/basic/detail',{questionid}),
    getExamPaper: () => http.post('/exam/app/exam/data'),
    getExamHistoryList: () => http.post('/exam/app/exam/history'),
    getExamHistoryStats: () => http.post('/exam/app/exam/stats'),
    getExerciseList: () => http.post('/exam/app/exercise/data'),
    getExerciseProgress: (pointid) => http.post('/exam/app/exercise/progress',{pointid}),
    getExerciseQuestion: (params) => http.post('/exam/app/exercise',params),
    verifyExamFace: (params) => http.post('/exam/app/session/verify',params),
    drawExamPaper: (params) => http.post('/exam/app/session/draw',params),
    getExamSession: (sessionId) => http.post('/exam/app/session/',{sessionId}),
    getReTestExamSession: (ehId) => http.post('/exam/app/session/retest',{ehId}),
    getExamSessionLeftTime:(sessionId) => http.post('/exam/app/session/time',{sessionId}),
    saveExamSessionAnswer: (params) => http.post('/exam/app/session/save',params),
    finishExamSession: (params) => http.post('/exam/app/session/finish',params),
    recoverExamSession: (sessionId) => http.post('/exam/app/session/recover',{sessionId}),
    dropExamSession: (sessionId) => http.post('/exam/app/session/drop',{sessionId}),
    getHistoryList: (params) => http.post('/exam/app/history/data',params),
    getHistoryStats: (ehid) => http.post('/exam/app/history',{ehid}),
    getHistoryDetail: (ehid) => http.post('/exam/app/history/detail',{ehid}),
    delHistory: (ehId) => http.post('/exam/app/history/delete',{ehId}),
    favorQuestion: (questionId) => http.post('/exam/app/favor/favor',{questionId}),
    unFavorQuestion: (questionId) => http.post('/exam/app/favor/unfavor',{questionId}),
    getFavorQuestionList: (params) => http.post('/exam/app/favor',params),
};
export default examApi;